language: ruby
sudo: false
rvm:
  - 2.2.2
bundler_args: --without production
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
before_script:
  # The Engine migrations are duplicated inside the spec/dummy app's migrations,
  # so `db:migrate` fails with error "Multiple migrations have the name". The
  # workaround is to run the setup from inside the spec/dummy folder.
  #
  # Also, no need to call `apartment:create_tenants` since our Rspec setup
  # creates the tenants needed in `spec/support/apartment`
  - "cd spec/dummy"
  - "rake db:create"
  - "rake db:migrate"
  - "cd ../.."
script: bundle exec rspec
services:
  - postgresql
addons:
  postgresql: "9.6"
