development: &default
  adapter: postgresql
  database: clockface_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: clockface_test
  <% if ENV.key?("RUNNING_ON_CI_SERVER") %>
  host: postgres
  user: runner
  password: ""
  <% end %>
